-- ================================================
-- 供花発注システム - スキーマ (P1)
-- Supabase SQL Editor で実行してください
-- ================================================

CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ================================================
-- 設定（単一行で運用）
-- ================================================
CREATE TABLE IF NOT EXISTS flower_settings (
    id                   integer PRIMARY KEY DEFAULT 1 CHECK (id = 1),
    site_base_url        text    NOT NULL DEFAULT '',        -- 供花サイトのベースURL
    order_deadline_hours integer NOT NULL DEFAULT 24,        -- 告別式の何時間前で受付を締め切るか
    notify_emails        text[]  NOT NULL DEFAULT '{}',      -- 受注通知の宛先
    tax_rate             numeric(4,3) NOT NULL DEFAULT 0.10, -- 供花の消費税率
    updated_at           timestamptz DEFAULT now()
);

INSERT INTO flower_settings (id) VALUES (1) ON CONFLICT (id) DO NOTHING;

-- ================================================
-- 供花商品マスタ
-- ================================================
CREATE TABLE IF NOT EXISTS flower_products (
    id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    code          text UNIQUE NOT NULL,
    name          text NOT NULL,
    description   text NOT NULL DEFAULT '',
    category      text NOT NULL DEFAULT '供花',
    price         integer NOT NULL CHECK (price >= 0),   -- 税抜・送料/設営費込み
    image_paths   text[]  NOT NULL DEFAULT '{}',         -- Storage バケット flower-images 内のパス
    display_order integer NOT NULL DEFAULT 0,
    is_active     boolean NOT NULL DEFAULT true,
    created_at    timestamptz DEFAULT now(),
    updated_at    timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS flower_products_display_order_idx
    ON flower_products (display_order);

-- ================================================
-- 葬儀（＝供花の受付単位）
-- ================================================
CREATE TABLE IF NOT EXISTS funerals (
    id                 uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    estimate_id        bigint REFERENCES estimates(id) ON DELETE SET NULL,
    deceased_name      text NOT NULL,
    chief_mourner_name text NOT NULL DEFAULT '',
    venue_name         text NOT NULL DEFAULT '',
    venue_address      text NOT NULL DEFAULT '',
    wake_at            timestamptz,                       -- 通夜
    ceremony_at        timestamptz,                       -- 告別式
    order_deadline     timestamptz,                       -- 告別式から自動計算
    public_token       text UNIQUE NOT NULL,              -- 発注URL用トークン
    is_order_open      boolean NOT NULL DEFAULT true,
    note               text NOT NULL DEFAULT '',
    created_at         timestamptz DEFAULT now(),
    updated_at         timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS funerals_ceremony_at_idx ON funerals (ceremony_at DESC);
CREATE INDEX IF NOT EXISTS funerals_estimate_id_idx ON funerals (estimate_id);

-- ================================================
-- 発注
-- ================================================
CREATE SEQUENCE IF NOT EXISTS flower_order_number_seq START 1;

CREATE TABLE IF NOT EXISTS flower_orders (
    id                       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_number             text UNIQUE NOT NULL
                               DEFAULT 'FO-' || lpad(nextval('flower_order_number_seq')::text, 6, '0'),
    funeral_id               uuid NOT NULL REFERENCES funerals(id) ON DELETE RESTRICT,
    orderer_name             text NOT NULL,
    orderer_kana             text NOT NULL DEFAULT '',
    orderer_company          text NOT NULL DEFAULT '',
    orderer_phone            text NOT NULL,
    orderer_email            text NOT NULL,
    orderer_postal_code      text NOT NULL DEFAULT '',
    orderer_address          text NOT NULL DEFAULT '',
    relation                 text NOT NULL DEFAULT '',
    payment_method           text NOT NULL CHECK (payment_method IN ('card', 'invoice')),
    payment_status           text NOT NULL DEFAULT 'pending'
                               CHECK (payment_status IN ('pending', 'paid', 'failed', 'refunded', 'cancelled')),
    order_status             text NOT NULL DEFAULT 'received'
                               CHECK (order_status IN ('received', 'confirmed', 'cancelled')),
    stripe_session_id        text,
    stripe_payment_intent_id text,
    subtotal                 integer NOT NULL,   -- 税抜合計
    tax                      integer NOT NULL,
    total                    integer NOT NULL,   -- 税込合計
    remarks                  text NOT NULL DEFAULT '',
    created_at               timestamptz DEFAULT now(),
    updated_at               timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS flower_orders_funeral_id_idx ON flower_orders (funeral_id);
CREATE INDEX IF NOT EXISTS flower_orders_created_at_idx ON flower_orders (created_at DESC);

-- ================================================
-- 発注明細（注文時点の内容をスナップショット保存）
-- ================================================
CREATE TABLE IF NOT EXISTS flower_order_items (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id     bigint NOT NULL REFERENCES flower_orders(id) ON DELETE CASCADE,
    product_id   uuid REFERENCES flower_products(id) ON DELETE SET NULL,
    product_code text NOT NULL,
    product_name text NOT NULL,
    unit_price   integer NOT NULL,          -- 税抜
    tax_rate     numeric(4,3) NOT NULL DEFAULT 0.10,
    quantity     integer NOT NULL CHECK (quantity > 0),
    nafuda_name  text NOT NULL DEFAULT ''   -- 名札の表記（自由テキスト1行）
);

CREATE INDEX IF NOT EXISTS flower_order_items_order_id_idx ON flower_order_items (order_id);

-- ================================================
-- updated_at トリガー（database.sql の関数を再利用）
-- ================================================
DROP TRIGGER IF EXISTS update_flower_settings_updated_at ON flower_settings;
CREATE TRIGGER update_flower_settings_updated_at BEFORE UPDATE ON flower_settings
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS update_flower_products_updated_at ON flower_products;
CREATE TRIGGER update_flower_products_updated_at BEFORE UPDATE ON flower_products
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS update_funerals_updated_at ON funerals;
CREATE TRIGGER update_funerals_updated_at BEFORE UPDATE ON funerals
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS update_flower_orders_updated_at ON flower_orders;
CREATE TRIGGER update_flower_orders_updated_at BEFORE UPDATE ON flower_orders
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ================================================
-- RLS
--   方針: 公開サイトは anon で直接アクセスさせない。
--   商品マスタのみ公開読み取りを許可し、葬儀情報・注文は Edge Function (service role) 経由とする。
-- ================================================
ALTER TABLE flower_settings    ENABLE ROW LEVEL SECURITY;
ALTER TABLE flower_products    ENABLE ROW LEVEL SECURITY;
ALTER TABLE funerals           ENABLE ROW LEVEL SECURITY;
ALTER TABLE flower_orders      ENABLE ROW LEVEL SECURITY;
ALTER TABLE flower_order_items ENABLE ROW LEVEL SECURITY;

-- 商品マスタ: 公開中の商品のみ誰でも閲覧可
DROP POLICY IF EXISTS "flower_products public read" ON flower_products;
CREATE POLICY "flower_products public read" ON flower_products
    FOR SELECT USING (is_active = true);

DROP POLICY IF EXISTS "flower_products staff all" ON flower_products;
CREATE POLICY "flower_products staff all" ON flower_products
    FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- 設定・葬儀・注文: スタッフ（ログイン済み）のみ
DROP POLICY IF EXISTS "flower_settings staff all" ON flower_settings;
CREATE POLICY "flower_settings staff all" ON flower_settings
    FOR ALL TO authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "funerals staff all" ON funerals;
CREATE POLICY "funerals staff all" ON funerals
    FOR ALL TO authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "flower_orders staff all" ON flower_orders;
CREATE POLICY "flower_orders staff all" ON flower_orders
    FOR ALL TO authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "flower_order_items staff all" ON flower_order_items;
CREATE POLICY "flower_order_items staff all" ON flower_order_items
    FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- ================================================
-- Storage: 商品画像バケット
-- ================================================
INSERT INTO storage.buckets (id, name, public)
VALUES ('flower-images', 'flower-images', true)
ON CONFLICT (id) DO NOTHING;

DROP POLICY IF EXISTS "flower images public read" ON storage.objects;
CREATE POLICY "flower images public read" ON storage.objects
    FOR SELECT USING (bucket_id = 'flower-images');

DROP POLICY IF EXISTS "flower images staff write" ON storage.objects;
CREATE POLICY "flower images staff write" ON storage.objects
    FOR INSERT TO authenticated WITH CHECK (bucket_id = 'flower-images');

DROP POLICY IF EXISTS "flower images staff update" ON storage.objects;
CREATE POLICY "flower images staff update" ON storage.objects
    FOR UPDATE TO authenticated USING (bucket_id = 'flower-images');

DROP POLICY IF EXISTS "flower images staff delete" ON storage.objects;
CREATE POLICY "flower images staff delete" ON storage.objects
    FOR DELETE TO authenticated USING (bucket_id = 'flower-images');
