-- ================================================
-- タスク進捗共有ページ（要件: docs/requirements-task-progress.md）
--
--   ・案件（estimates）ごとに「やることリスト」を持たせる
--   ・喪主とスタッフが同じデータを別の見え方で参照する
--   ・喪主は案件ごとに発行したID/パスワードでログインする
--     （公開サイトからは Edge Function `task-public` 経由でのみ触る）
--
--   実行順の注意（供花のときと同じ）
--     1. このファイルを実行
--     2. npx supabase functions deploy task-public
--     3. 喪主サイトをデプロイ
-- ================================================

CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ================================================
-- タスクマスタ（生成条件つき）
-- ================================================
CREATE TABLE IF NOT EXISTS case_task_templates (
    id                 uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    code               text UNIQUE NOT NULL,
    title              text NOT NULL,
    description        text NOT NULL DEFAULT '',        -- 喪主向けの補足説明
    phase              text NOT NULL
                         CHECK (phase IN ('meeting', 'prepare', 'day', 'payment', 'after')),
    owner              text NOT NULL CHECK (owner IN ('fl', 'mourner', 'both')),
    visible_to_mourner boolean NOT NULL DEFAULT true,

    -- ---- 生成条件（すべて空なら常に生成）----
    --   「オプションが選択済みか」は条件に使わない。
    --   タスクは「まだ決まっていないことを決める」ためのもので、条件が逆向きになるため。
    target_categories  text[]    NOT NULL DEFAULT '{}',  -- 'funeral' | 'cremation'
    target_plan_ids    text[]    NOT NULL DEFAULT '{}',  -- plans.id
    related_item_id    integer   REFERENCES items(id) ON DELETE SET NULL,
    require_flower     boolean   NOT NULL DEFAULT false, -- 供花の受付があるときだけ生成

    -- ---- 期日・自動完了 ----
    due_offset_days    integer,                          -- 告別式日からの相対日数（負=前）
    auto_complete_on   text CHECK (auto_complete_on IN ('quote', 'invoice', 'receipt')),

    initial_status     text NOT NULL DEFAULT 'todo'
                         CHECK (initial_status IN ('todo', 'done')),
    sort_order         integer NOT NULL DEFAULT 0,
    is_active          boolean NOT NULL DEFAULT true,
    created_at         timestamptz DEFAULT now(),
    updated_at         timestamptz DEFAULT now()
);

COMMENT ON COLUMN case_task_templates.related_item_id IS
    '関連オプション。①そのアイテムが案件のプランで選べない場合はタスクを生成しない '
    '②タスクから画像カタログ（/?catalog=true&item=<id>）を開く導線に使う。'
    '「選択済みかどうか」は生成条件にしない（完了の目安として表示するのみ）';

CREATE INDEX IF NOT EXISTS case_task_templates_sort_idx
    ON case_task_templates (sort_order) WHERE is_active;

-- ================================================
-- 案件ごとのタスク
--   マスタからコピーして実体化する（供花の flower_order_items と同じ考え方）。
--   あとからマスタを直しても進行中の案件は変わらない。
-- ================================================
CREATE TABLE IF NOT EXISTS case_tasks (
    id                   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    estimate_id          bigint NOT NULL REFERENCES estimates(id) ON DELETE CASCADE,
    template_id          uuid REFERENCES case_task_templates(id) ON DELETE SET NULL,
    code                 text NOT NULL,
    title                text NOT NULL,
    description          text NOT NULL DEFAULT '',
    phase                text NOT NULL,
    owner                text NOT NULL CHECK (owner IN ('fl', 'mourner', 'both')),
    visible_to_mourner   boolean NOT NULL DEFAULT true,
    related_item_id      integer,

    status               text NOT NULL DEFAULT 'todo'
                           CHECK (status IN ('todo', 'doing', 'done', 'skipped')),
    due_at               timestamptz,
    assignee_name        text NOT NULL DEFAULT '',   -- 誰が予約したかを残す（属人化の解消）
    staff_note           text NOT NULL DEFAULT '',   -- 社内メモ。喪主には返さない
    shared_note          text NOT NULL DEFAULT '',   -- 喪主にも見せる連絡事項

    -- 喪主のチェックは「確認済み」。完了の確定はスタッフが行う
    mourner_confirmed_at timestamptz,

    completed_at         timestamptz,
    completed_by_role    text CHECK (completed_by_role IN ('staff', 'system')),
    completed_by_name    text NOT NULL DEFAULT '',
    auto_complete_on     text,                       -- 帳票の発行で自動完了させる指定

    -- ---- v2 用のフック（v1では使わない）----
    attachment_paths     text[] NOT NULL DEFAULT '{}',  -- 死亡診断書PDFなど
    notify_on_complete   boolean NOT NULL DEFAULT false,

    sort_order           integer NOT NULL DEFAULT 0,
    created_at           timestamptz DEFAULT now(),
    updated_at           timestamptz DEFAULT now(),
    UNIQUE (estimate_id, code)
);

CREATE INDEX IF NOT EXISTS case_tasks_estimate_id_idx ON case_tasks (estimate_id, sort_order);
CREATE INDEX IF NOT EXISTS case_tasks_due_at_idx      ON case_tasks (due_at) WHERE status <> 'done';

-- ================================================
-- 更新履歴（誰がいつ動かしたか）
-- ================================================
CREATE TABLE IF NOT EXISTS case_task_events (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id    bigint NOT NULL REFERENCES case_tasks(id) ON DELETE CASCADE,
    action     text NOT NULL,      -- 'status' | 'confirm' | 'note' | 'due' | 'assignee'
    from_value text,
    to_value   text,
    actor_role text NOT NULL CHECK (actor_role IN ('staff', 'mourner', 'system')),
    actor_name text NOT NULL DEFAULT '',
    created_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS case_task_events_task_id_idx
    ON case_task_events (task_id, created_at DESC);

-- ================================================
-- 喪主のログイン情報
--   平文のパスワードは保存しない。発行直後の1回だけ画面に出す。
-- ================================================
CREATE TABLE IF NOT EXISTS case_credentials (
    id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    estimate_id   bigint UNIQUE NOT NULL REFERENCES estimates(id) ON DELETE CASCADE,
    login_id      text UNIQUE NOT NULL,
    password_hash text NOT NULL,
    is_active     boolean NOT NULL DEFAULT true,
    expires_at    timestamptz,          -- NULL = 無期限（葬儀後サポートへ繋ぐため既定は止めない）
    issued_at     timestamptz DEFAULT now(),
    issued_by     text NOT NULL DEFAULT '',
    last_login_at timestamptz,
    -- ---- v2 用のフック ----
    line_user_id  text,
    contact_email text
);

-- ================================================
-- セッション
--   Edge Function（service role）からのみ触る。RLSポリシーは作らない。
-- ================================================
CREATE TABLE IF NOT EXISTS case_sessions (
    token       text PRIMARY KEY,
    estimate_id bigint REFERENCES estimates(id) ON DELETE CASCADE,  -- staff は NULL
    role        text NOT NULL CHECK (role IN ('mourner', 'staff')),
    actor_name  text NOT NULL DEFAULT '',
    expires_at  timestamptz NOT NULL,
    created_at  timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS case_sessions_expires_at_idx ON case_sessions (expires_at);

-- ================================================
-- updated_at トリガー（database.sql の関数を再利用）
-- ================================================
DROP TRIGGER IF EXISTS update_case_task_templates_updated_at ON case_task_templates;
CREATE TRIGGER update_case_task_templates_updated_at BEFORE UPDATE ON case_task_templates
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS update_case_tasks_updated_at ON case_tasks;
CREATE TRIGGER update_case_tasks_updated_at BEFORE UPDATE ON case_tasks
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ================================================
-- RLS
--   方針は migrations/011_close_rls.sql と同じ。業務データは authenticated のみ。
--   喪主サイトは Edge Function（service role）経由でのみアクセスする。
-- ================================================
ALTER TABLE case_task_templates ENABLE ROW LEVEL SECURITY;
ALTER TABLE case_tasks          ENABLE ROW LEVEL SECURITY;
ALTER TABLE case_task_events    ENABLE ROW LEVEL SECURITY;
ALTER TABLE case_credentials    ENABLE ROW LEVEL SECURITY;
ALTER TABLE case_sessions       ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "case_task_templates staff all" ON case_task_templates;
CREATE POLICY "case_task_templates staff all" ON case_task_templates
    FOR ALL TO authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "case_tasks staff all" ON case_tasks;
CREATE POLICY "case_tasks staff all" ON case_tasks
    FOR ALL TO authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "case_task_events staff all" ON case_task_events;
CREATE POLICY "case_task_events staff all" ON case_task_events
    FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- 発行UIが見積システム側にあるため authenticated には開ける。
-- password_hash は画面では扱わない。
DROP POLICY IF EXISTS "case_credentials staff all" ON case_credentials;
CREATE POLICY "case_credentials staff all" ON case_credentials
    FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- case_sessions はポリシーを作らない（RLS有効＋ポリシーなし = service role 以外は不可）

-- ================================================
-- タスクマスタの初期データ
--   related_item_id は items が未投入でもエラーにならないよう副問い合わせで引く。
-- ================================================
INSERT INTO case_task_templates
    (code, title, description, phase, owner, visible_to_mourner,
     target_categories, related_item_id, require_flower,
     due_offset_days, auto_complete_on, initial_status, sort_order, is_active)
VALUES
    ('transport', 'ご搬送', '病院・ご自宅から安置先へのご搬送です。',
     'meeting', 'fl', true, '{}', (SELECT id FROM items WHERE id = 1), false,
     NULL, NULL, 'done', 10, true),

    ('keeping', 'ご安置', '火葬・ご葬儀までの間、お預かりいたします。',
     'meeting', 'fl', true, '{}', (SELECT id FROM items WHERE id = 3), false,
     NULL, NULL, 'done', 20, true),

    ('temple_check', '菩提寺（お坊さん）の確認',
     '代々のお寺やお墓がある場合は、まずお寺様のご都合をご確認ください。ここが決まらないと日程が確定できません。',
     'meeting', 'mourner', true, '{}', NULL, false,
     -5, NULL, 'todo', 30, true),

    ('schedule', '日程（通夜・告別式・火葬）の決定', '火葬場・斎場の空き状況をふまえて決定します。',
     'meeting', 'both', true, '{}', NULL, false,
     -5, NULL, 'todo', 40, true),

    ('venue_booking', '斎場・火葬場の予約', '確定した日程で予約を取ります。',
     'meeting', 'fl', true, '{}', (SELECT id FROM items WHERE id = 40), false,
     -4, NULL, 'todo', 50, true),

    ('plan', 'プランの決定', 'ご希望とご予算に合わせてプランを決定します。',
     'meeting', 'both', true, '{}', NULL, false,
     -4, NULL, 'todo', 60, true),

    ('altar', '祭壇の決定', '写真をご覧のうえ、ご希望をお知らせください。',
     'prepare', 'both', true, '{}', (SELECT id FROM items WHERE id = 31), false,
     -3, NULL, 'todo', 70, true),

    ('coffin', 'お棺の決定', '写真をご覧のうえ、ご希望をお知らせください。',
     'prepare', 'both', true, '{}', (SELECT id FROM items WHERE id = 30), false,
     -3, NULL, 'todo', 80, true),

    ('portrait', '遺影写真のお預かり', 'スマートフォンのお写真でも承ります。',
     'prepare', 'both', true, '{}', (SELECT id FROM items WHERE id = 33), false,
     -3, NULL, 'todo', 90, true),

    ('urn', '骨壷の決定', '',
     'prepare', 'both', true, '{}', (SELECT id FROM items WHERE id = 34), false,
     -2, NULL, 'todo', 100, true),

    ('flower', '供花の取りまとめ', 'ご親族・ご関係先からのお申し込みを取りまとめます。',
     'prepare', 'both', true, '{}', (SELECT id FROM items WHERE id = 32), true,
     -1, NULL, 'todo', 110, true),

    ('death_notice', '死亡届（＋診断書のコピー保管）',
     '役所への提出を代行します。診断書のコピーは当社で保管し、お渡しいたします。',
     'prepare', 'fl', true, '{}', (SELECT id FROM items WHERE id = 6), false,
     -3, NULL, 'todo', 120, true),

    ('invitation', '儀式案内状 / 当日タイムスケジュール', 'ご会葬の皆さまへのご案内です。',
     'prepare', 'both', true, '{funeral}', (SELECT id FROM items WHERE id = 16), false,
     -3, NULL, 'todo', 130, true),

    ('greeting_gift', '御挨拶状 / 当日返礼品', '',
     'prepare', 'both', true, '{}', (SELECT id FROM items WHERE id = 50), false,
     -2, NULL, 'todo', 140, true),

    ('catering', '料理 / 香典返し', 'カタログの品番をお知らせください。',
     'prepare', 'both', true, '{funeral}', (SELECT id FROM items WHERE id = 52), false,
     -2, NULL, 'todo', 150, true),

    -- 社内作業。喪主には表示しない。
    -- 菩提寺の有無は現状「お布施・戒名料」の入力で推し量る。
    -- A-6 で商談画面に「お坊さんの有無」フラグが入ったら条件を差し替える。
    ('temple_fax', '坊さん連絡FAX', '',
     'prepare', 'fl', false, '{}', (SELECT id FROM items WHERE id = 53), false,
     -2, NULL, 'todo', 160, true),

    -- アイテム未登録のため既定で無効（8/6定例 A-7 でオプション商品化を検討中）
    ('movie', '思い出ムービー', '',
     'prepare', 'both', true, '{}', NULL, false,
     -2, NULL, 'todo', 170, false),

    ('endroll', '当日エンドロール', '',
     'day', 'fl', true, '{}', NULL, false,
     0, NULL, 'todo', 180, false),

    ('invoice_sent', '請求書の送付', '',
     'payment', 'fl', true, '{}', NULL, false,
     3, 'invoice', 'todo', 190, true),

    ('payment_received', 'お支払い（入金の確認）', 'お振込みの確認をもって完了となります。',
     'payment', 'both', true, '{}', NULL, false,
     21, 'receipt', 'todo', 200, true)
ON CONFLICT (code) DO NOTHING;

-- ================================================
-- 確認用
-- ================================================
SELECT sort_order, code, title, phase, owner, visible_to_mourner,
       related_item_id, require_flower, due_offset_days, auto_complete_on,
       initial_status, is_active
FROM case_task_templates
ORDER BY sort_order;

SELECT tablename, policyname, roles, cmd
FROM pg_policies
WHERE schemaname = 'public'
  AND tablename LIKE 'case_%'
ORDER BY tablename, policyname;
